# Allow longer line widths, so that error messages don't get cut off, because this could break a test case.
# Note: rustfmt is very picky about trailing comments and might move a comment to the next line anyway :'-(
max_width = 1000
wrap_comments = false
comment_width = 1000